const { ethers, artifacts } = require("hardhat");
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

/**
 * Computes the SHA-256 hash of the official ALU logo file and returns it
 * formatted as a bytes32 hex string (0x-prefixed, 32 bytes / 64 hex chars).
 */
function computeLogoHash() {
  const logoPath = path.join(__dirname, "..", "alu-logo.png");
  const fileBuffer = fs.readFileSync(logoPath);
  const hash = crypto.createHash("sha256").update(fileBuffer).digest("hex");
  return "0x" + hash;
}

/**
 * Writes contract addresses, ABIs and the registered logo hash to a single
 * config file that the plain-JS frontend loads directly (no bundler needed).
 */
async function writeFrontendConfig(registryAddress, tokenAddress, logoHash, network) {
  const registryArtifact = await artifacts.readArtifact("ALUAssetRegistry");
  const tokenArtifact = await artifacts.readArtifact("ALULogoToken");

  const config = {
    network,
    aluAssetRegistry: {
      address: registryAddress,
      abi: registryArtifact.abi
    },
    aluLogoToken: {
      address: tokenAddress,
      abi: tokenArtifact.abi
    },
    officialLogoTokenId: 1,
    officialLogoHash: logoHash
  };

  const outDir = path.join(__dirname, "..", "frontend", "js");
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
  const outPath = path.join(outDir, "contract-config.js");
  const contents =
    "// AUTO-GENERATED by scripts/deploy.js — do not edit by hand.\n" +
    "// Re-run `npm run deploy:local` after every fresh Hardhat node restart\n" +
    "// to regenerate this file with fresh addresses.\n" +
    "window.ALU_CONTRACT_CONFIG = " + JSON.stringify(config, null, 2) + ";\n";
  fs.writeFileSync(outPath, contents);
  console.log("Frontend config written to:", outPath);
}

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying contracts with the account:", deployer.address);

  // 1. Deploy ALUAssetRegistry
  const ALUAssetRegistry = await ethers.getContractFactory("ALUAssetRegistry");
  const assetRegistry = await ALUAssetRegistry.deploy();
  await assetRegistry.waitForDeployment();
  const registryAddress = await assetRegistry.getAddress();
  console.log("ALUAssetRegistry deployed to:", registryAddress);

  // 2. Compute the REAL SHA-256 hash of the official logo file and register it.
  //    (Formative 1 used a placeholder hardcoded hash here — that has been
  //    fixed so the deployed registration always matches the actual file.)
  const aluLogoHash = computeLogoHash();
  console.log("Computed ALU logo SHA-256 hash:", aluLogoHash);

  console.log("Registering ALU Logo asset...");
  const tx = await assetRegistry.registerAsset(
    "ALU Official Logo",
    "png",
    aluLogoHash
  );
  await tx.wait();
  console.log("ALU Logo successfully registered in the asset registry (tokenId 1).");

  // 3. Deploy ALULogoToken, passing the deployer as the initial owner
  const ALULogoToken = await ethers.getContractFactory("ALULogoToken");
  const logoToken = await ALULogoToken.deploy(deployer.address);
  await logoToken.waitForDeployment();
  const tokenAddress = await logoToken.getAddress();
  console.log("ALULogoToken deployed to:", tokenAddress);
  console.log("1,000,000 ALUT tokens minted to:", deployer.address);

  // 4. Write everything the frontend needs into a single config file
  const network = await ethers.provider.getNetwork();
  await writeFrontendConfig(registryAddress, tokenAddress, aluLogoHash, {
    name: network.name,
    chainId: Number(network.chainId)
  });

  console.log("\nDeployment complete. Start the frontend with `npm run serve` and open http://localhost:8080");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
